spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./db/shareit
    username: test
    password: test
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE