db:
  name: shareit
  port: 5432

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${db.port}/${db.name}
    username: root
    password: root

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  config:
    activate:
      on-profile: ci, test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./db/${db.name}
    username: test
    password: test




