CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(150) NOT NULL,
    email VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description  VARCHAR(1000) NOT NULL,
    requester_id BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created      TIMESTAMP     NOT NULL,
    CONSTRAINT pk_item_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(200)  NOT NULL,
    description VARCHAR(1000) NOT NULL,
    available   BOOLEAN       NOT NULL,
    owner_id    BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    request_id  BIGINT REFERENCES requests (id),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    start_time TIMESTAMP   NOT NULL,
    end_time   TIMESTAMP   NOT NULL,
    item_id    BIGINT      NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    booker_id  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status     varchar(30) NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text      VARCHAR(500) NOT NULL,
    item_id   BIGINT       NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    author_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);